-- ============================================================
-- One3 Stay — migration v2
-- Run this in Supabase SQL Editor (Project > SQL Editor > New query)
-- Safe to re-run: every statement uses IF NOT EXISTS / IF EXISTS.
-- ============================================================

-- 1) PROPERTIES: pinning, manual sort order, sharing-friendly slug
alter table properties add column if not exists pinned boolean default false;
alter table properties add column if not exists sort_order integer default 0;

-- 2) ROOMS: pinning/order (kept simple, inherits property's category)
alter table rooms add column if not exists sort_order integer default 0;

-- 3) TIFFIN: order
alter table tiffin add column if not exists sort_order integer default 0;

-- 4) INVENTORY: order
alter table inventory add column if not exists sort_order integer default 0;

-- 5) SETTINGS — single key/value table for site-wide config
--    (business name, default category shown first, owner WhatsApp for
--     Connect & Services tab, etc.)
create table if not exists settings (
  key text primary key,
  value text
);

insert into settings (key, value) values
  ('business_name', 'One3 Stay'),
  ('default_category', 'all'),
  ('owner_whatsapp', '919999900000')
on conflict (key) do nothing;

-- 6) SERVICES — the "extra services we provide" directory
create table if not exists services (
  id bigint generated by default as identity primary key,
  name text not null,
  icon text default '🔧',
  whatsapp text,              -- leave blank to use owner_whatsapp from settings
  active boolean default true,
  sort_order integer default 0,
  created_at timestamptz default now()
);

insert into services (name, icon, sort_order) values
  ('Rental & Legal Drafting', '📝', 1),
  ('Trademark Registration', '®️', 2),
  ('Website Building', '💻', 3),
  ('Packers & Movers', '📦', 4),
  ('RO / AC Service', '❄️', 5),
  ('Electrician', '🔌', 6),
  ('Cleaning Service', '🧹', 7),
  ('Lift Service', '🛗', 8),
  ('Tile Installation', '🧱', 9),
  ('Interior Consultation', '🛋️', 10),
  ('End-to-End PG / Rental Maintenance', '🛠️', 11),
  ('Gemstones', '💎', 12),
  ('Bulk Anaj & Spices', '🌾', 13),
  ('Bulk Building Material', '🏗️', 14)
on conflict do nothing;

-- 7) INQUIRIES — public "List your property / general query" form
--    (create if your project doesn't already have it)
create table if not exists inquiries (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  role text,                 -- broker / tenant / owner / supplier / interior / lawyer / general
  message text,
  handled boolean default false,
  created_at timestamptz default now()
);

-- 8) ROW LEVEL SECURITY
-- Public site uses the anon key, which is meant to be public — real
-- protection comes from these policies, NOT from hiding the key.
alter table properties enable row level security;
alter table rooms enable row level security;
alter table tiffin enable row level security;
alter table inventory enable row level security;
alter table services enable row level security;
alter table settings enable row level security;
alter table inquiries enable row level security;

-- Anyone can READ listings/services/settings
drop policy if exists "public read properties" on properties;
create policy "public read properties" on properties for select using (true);

drop policy if exists "public read rooms" on rooms;
create policy "public read rooms" on rooms for select using (true);

drop policy if exists "public read tiffin" on tiffin;
create policy "public read tiffin" on tiffin for select using (true);

drop policy if exists "public read inventory" on inventory;
create policy "public read inventory" on inventory for select using (true);

drop policy if exists "public read services" on services;
create policy "public read services" on services for select using (true);

drop policy if exists "public read settings" on settings;
create policy "public read settings" on settings for select using (true);

-- Anyone can INSERT an inquiry (the public form), nobody can read others' inquiries
drop policy if exists "public insert inquiries" on inquiries;
create policy "public insert inquiries" on inquiries for insert with check (true);

-- Only logged-in admin (you) can write/edit/delete anything
drop policy if exists "admin write properties" on properties;
create policy "admin write properties" on properties for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "admin write rooms" on rooms;
create policy "admin write rooms" on rooms for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "admin write tiffin" on tiffin;
create policy "admin write tiffin" on tiffin for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "admin write inventory" on inventory;
create policy "admin write inventory" on inventory for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "admin write services" on services;
create policy "admin write services" on services for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "admin write settings" on settings;
create policy "admin write settings" on settings for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "admin read inquiries" on inquiries;
create policy "admin read inquiries" on inquiries for select using (auth.role() = 'authenticated');

drop policy if exists "admin write inquiries" on inquiries;
create policy "admin write inquiries" on inquiries for update using (auth.role() = 'authenticated');

drop policy if exists "admin delete inquiries" on inquiries;
create policy "admin delete inquiries" on inquiries for delete using (auth.role() = 'authenticated');

-- Done. Next: open admin.html, log in, and check Settings tab to set
-- your business name, default category and main WhatsApp number.
